layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

repository: MarcoBuster/personal-website
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  include:
    - python-botogram/botogram
    - tdlight-team/tdlight-telegram-bot-api
    - MarcoBuster/OrarioTreniBot
    - MarcoBuster/ClasseVivaAPI
    - MarcoBuster/AoC
    - MarcoBuster/university
    - MarcoBuster/unihome
    - MarcoBuster/immuni-tek-sender
    - MarcoBuster/data-clustering-contest

social_media:
  telegram: MarcoBuster
  youtube: UCE27OjiqihFuKnC6GZnndiQ
  twitter: realMarcoBuster
  stackoverflow: 6083563
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

topics:
  - name: Electronic Frontier Foundation
    web_url: https://eff.org
    image_url: /assets/img/home/eff.jpg

  - name: Free Software Foundation
    web_url: https://fsf.org
    image_url: /assets/img/home/fsf.jpg

  - name: Telegram Messenger
    web_url: https://telegram.org
    image_url: /assets/img/home/telegram.jpg

  - name: Python Software Foundation
    web_url: https://www.python.org/psf/
    image_url: /assets/img/home/python.jpg

  - name: Golang
    web_url: https://golang.org/
    image_url: /assets/img/home/golang.jpg

  - name: Monero cryptocurrency
    web_url: https://getmonero.org
    image_url: /assets/img/home/monero.jpg
